name: Check update log

on:
  push:
    branches:
      - feature**

jobs:
  check:
    name: check update log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Check update log
        uses: technote-space/get-diff-action@v6
        id: check-diff
        with:
          # 対象ファイル
          FILES: |
            CHANGELOG.md
            update.json
            build.gradle
      - name: Lift Protection
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/Rin0530/Itomon-Mod/statuses/${{ github.sha }} \
          -d '{state: "success", context: "update version"}'
        if: env.GIT_DIFF